// Copyright (C) 2014 dot42
//
// Original filename: XmlArrayItemAttribute.cs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
using System.Xml.Schema;

namespace System.Xml.Serialization
{
    /// <summary>
    /// Represents an attribute that specifies the derived types that the XmlSerializer can place in a serialized array.
    /// </summary>
[AttributeUsageAttribute(AttributeTargets.Property|AttributeTargets.Field|AttributeTargets.Parameter|AttributeTargets.ReturnValue, AllowMultiple = true)]    public class XmlArrayItemAttribute : Attribute
    {
        private string elementName;
        private string dataType;

        /// <summary>
        /// Default ctor
        /// </summary>
        public XmlArrayItemAttribute()
        {            
        }

        /// <summary>
        /// Element name ctor
        /// </summary>
        public XmlArrayItemAttribute(string elementName)
        {
            this.elementName = elementName;
        }

        /// <summary>
        /// Type ctor
        /// </summary>
        public XmlArrayItemAttribute(Type type)
        {
            Type = type;
        }

        /// <summary>
        /// Element name + type ctor
        /// </summary>
        public XmlArrayItemAttribute(string elementName, Type type)
        {
            this.elementName = elementName;
            Type = type;
        }

        /// <summary>
        /// Gets/sets the name of the generated XML element.
        /// </summary>
        public string ElementName
        {
            get { return elementName ?? string.Empty; }
            set { elementName = value; }
        }

        /// <summary>
        /// Gets/sets the namespace of the XML element.
        /// </summary>
        public string Namespace { get; set; }

        /// <summary>
        /// Gets/sets the XML data type of the generated XML element.
        /// </summary>
        public string DataType
        {
            get { return dataType ?? string.Empty; }
            set { dataType = value; }
        }

        /// <summary>
        /// Gets/sets whether the XML element name generated by the XmlSerializer is qualified or unqualified.
        /// </summary>
        public XmlSchemaForm Form { get; set; }

        /// <summary>
        /// Gets/sets whether the XmlSerializer must serialize a member as an empty XML tag with the xsi:nil attribute set to true.
        /// </summary>
        public bool IsNullable { get; set; }

        /// <summary>
        /// Gets or sets the level in a hierarchy of XML elements that the XmlArrayItemAttribute affects.
        /// </summary>
        public int NestingLevel { get; set; }

        /// <summary>
        /// Gets/sets the type allowed in an array.
        /// </summary>
        public Type Type { get; set; }
    }
}

