// Copyright (C) 2014 dot42
//
// Original filename: XmlSerializerVersionAttribute.cs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
namespace System.Xml.Serialization
{
    /// <summary>
    /// Signifies that the code was generated by the serialization infrastructure and can be reused for increased performance, when this attribute is applied to an assembly.
    /// </summary>
    [AttributeUsageAttribute(AttributeTargets.Assembly)]
    public class XmlSerializerVersionAttribute : Attribute
    {
        /// <summary>
        /// Default ctor
        /// </summary>
        public XmlSerializerVersionAttribute()
        {
        }

        /// <summary>
        /// Type ctor
        /// </summary>
        public XmlSerializerVersionAttribute(Type type)
        {
            Type = type;
        }

        /// <summary>
        /// Gets/sets the common language runtime (CLR) namespace of the assembly.
        /// </summary>
        public string Namespace { get; set; }

        /// <summary>
        /// Gets or sets the identity of the parent assembly.
        /// </summary>
        public string ParentAssemblyId { get; set; }

        /// <summary>
        /// Gets/sets the assembly's version number.
        /// </summary>
        public string Version { get; set; }

        /// <summary>
        /// Gets/sets the type that the serializer operates on.
        /// </summary>
        public Type Type { get; set; }
    }
}

